### PR TITLE
fix: Fixed templates related to parseUrl exception and fixed wrong bookmarks variable in js

### PR DESCRIPTION
**Pull request by bresam**
- Template rendering is fixed by replacement and simplification of html template tag
 - Added missing html templates for some controller actions used by ajax
 - fixed a wrong variable name in js

### CODE REVIEW

**Comment by bresam** [comment]
@buepro This PR finally fixes all issues related to T3v11

**Comment by bresam** [comment]
Tested with localStorage and dbStorage

**Comment by bresam** [comment]
@buepro Thank you for merging. Is it possible to create a new release/tag?

**Comment by buepro** [comment]
@bresam Just released v3. Do you need it as well on TER?

**Comment by bresam** [comment]
Would be nice to have it on TER too. Thank you

**Pull request merged**
