### PR TITLE
feat: make compatible with TYPO3 v11

### PR DESCRIPTION
**Pull request by maikschneider**
This PR will make the extension compatible with TYPO3 v11

* Applied rector to tidy up code
* Re-added HTML output to Ajax response
* Removed unused version checks
* Renamed TypoScript files

### CODE REVIEW

**Comment by neufeind** [comment]
We're also looking into using the extension with TYPO3 v11. Would love to see this cleanup considered. Some changes seem to slightly enhance/extend current functionality (like adding "list" to the json-data). Maybe that should go into a separate changeset to be considered separately. And maybe "Bookmarks" could become more of a Repository as being called a Model - but that's independent of the TYPO3 v11-compatibility as well.

Would love to get this pull-request going, and I'll be willing to help. Thanks for your work.

**Comment by bresam** [comment]
@buepro any chance this will get merged to master?

**Comment by buepro** [comment]
@maikschneider Thank you very much for your PR!
@bresam Do you have the chance to test the merged state?

**Comment by dwitassek** [comment]
@bresam and I did test the merge on T3 v11.5.36. Basically, it is installable and seems to work. But there are still some problems. If we upgrade an existing installation without any database changes and using the standard FLUID templates, we get the following error in the frontend:

> (1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
> PHP Runtime Deprecation Notice: parse_url(): Passing null to parameter #1 ($url) of type string is deprecated in /var/www/app/public/typo3/sysext/fluid/Classes/ViewHelpers/Link/ExternalViewHelper.php line 78

The problem seems to hide in the FLUID templating. If we change line 18 in `/bookmark_pages/Resources/Private/Layouts/Default.html `

from

`<f:render partial="ListItem" arguments="{bookmark: bookmark}" />`

to

```
<f:for as="bookmark" each="{bookmarks}">
  <f:render partial="ListItem" arguments="{bookmark: bookmark}" />
</f:for>

```

we get rid of the frontend error and the extension basically runs, but JS throws some errors by adding or deleting items.

It seems that line 68 in `/bookmark_pages/Resources/Public/Scripts/JavaScript/bookmark_pages.js` must be changed from

`return typeof this.list[bookmark.id] === 'object';`

to

`return typeof this.list[bookmarks.id] === 'object';`

At least it is doing something, but deleting and adding is still not working properly, and with these changes the bookmark items are shown multiple times. So the for loop in FLUID is probably not the solution, but without it an empty parameter is given to the Viewhelper.

We didn't do a deeper dive till now, since we did not understand exactly the concept of repopulating the data again by Ajax. So before we go further here, maybe @maikschneider could give some hints, since he did already all the work for the updated version and knows the concepts better as we do for sure.

**Pull request merged**
